---
title: "EDA"
format: pdf
editor: visual
author: Sophia Yang
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(viridis)
```

```{r}
#| label: load-data
#| include: false

df <- readRDS("data/model_df.rds") |>
  mutate(is_SU = as.numeric(is_SU) - 1)
eda_df <- readRDS("data/eda_df.rds")
```

## Finalized EDA Plots

```{r}
prop_df <- eda_df |>
  group_by(term_enrolled) |>
  summarise(prop_passfail = mean(is_SU), .groups = "drop") |>
  mutate(highlight = if_else(term_enrolled == "Spring 2020", "highlight", "other"))

count_df <- eda_df |>
  group_by(term_enrolled) |>
  summarise(
  passfail_count = sum(is_SU),
  total = n(),
    .groups = "drop"
  ) |>
  mutate(highlight = if_else(term_enrolled == "Spring 2020", "highlight", "other"))

prop_su_plot <- ggplot(prop_df, 
       aes(x = term_enrolled, y = prop_passfail, fill = highlight)
      ) +
  geom_col() +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("highlight" = "red", "other" = "gray")) +
  labs(
    title = "Proportion of S/U Grades by Term",
    x = "Term Enrolled",
    y = "Proportion (S/U)"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
prop_su_plot
ggsave("figures/prop_su_plot.png", plot = prop_su_plot, dpi = 300)

ggplot(count_df, 
       aes(x = term_enrolled, y = passfail_count, fill = highlight)
      ) +
  geom_col() +
  scale_fill_manual(values = c("highlight" = "red", "other" = "gray")) +
  labs(
    title = "Count of S/U Grades by Term",
    x = "Term Enrolled",
    y = "Count (S/U)"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
grade_order <- c("A", "B", "C", "S", "D", "AD", "No Credit")
grade_prop <- eda_df |>
  filter(!final_grade %in% c("HP", "Z", "TNC", "WA", "X", "N", "I", "CR", "WE")) |>
  mutate(
    final_grade = case_when(
      str_starts(final_grade, "A") ~ "A",
      str_starts(final_grade, "B") ~ "B",
      str_starts(final_grade, "C") ~ "C",
      str_starts(final_grade, "D") ~ "D",
      final_grade %in% c("S", "P") ~ "S",
      final_grade %in% c("F", "I", "U", "W", "W*", "WF", "WP") ~ "No Credit",
      TRUE ~ final_grade
    ),
    final_grade = factor(
      final_grade,
      levels = grade_order,
      ordered = TRUE,
    )
  ) |>
  group_by(term_enrolled, final_grade) |>
  summarise(count = n(), .groups = "drop_last") |>
  mutate(prop = count / sum(count))

ggplot(grade_prop, aes(x = term_enrolled, y = prop, fill = final_grade)) +
  geom_col(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_viridis(discrete = TRUE) +
  labs(
    title = "Distribution of Grades by Term",
    x = "Term Enrolled",
    y = "Proportion of Grades",
    fill = "Grade Group",
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

grade_dist_plot <- ggplot(grade_prop, aes(x = term_enrolled, y = prop, 
                       group = final_grade, color = final_grade)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_viridis(discrete = TRUE) +
  labs(
    title = "Distribution of Grades by Term",
    x = "Term Enrolled",
    y = "Proportion of Grades",
    color = "Grade Group",
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
grade_dist_plot
ggsave("figures/grade_dist_plot.png", plot = grade_dist_plot, dpi = 300)
```

```{r}
#| fig-width: 7
#| fig-height: 4
df_props <- df |> 
  group_by(masked_student_ID) |> 
  mutate(total_num_SU = sum(is_SU, na.rm = TRUE)) |> 
  ungroup() |> 
  count(student_group, total_num_SU) |> 
  group_by(student_group) |> 
  mutate(prop = n / sum(n)) |> 
  ungroup() |> 
  mutate(
    graduated = ifelse(student_group >= 2022, "Continuing", "Graduated")
  )

total_su_plot <- ggplot(df_props, aes(
    x = student_group,
    y = prop,
    color = factor(total_num_SU),
    group = total_num_SU)) +
  geom_line(aes(linetype = "Continuing"), linewidth = 0.6) +
  geom_line(
    data = df_props |> filter(graduated == "Graduated"),
    aes(linetype = "Graduated"),
    linewidth = 0.8
  ) +
  geom_point() +
  scale_linetype_manual(
    values = c("Continuing" = "dashed", "Graduated" = "solid"),
    name = "Graduation Status"
  ) +
  scale_x_continuous(breaks = unique(df_props$student_group)) +
  labs(
    title = "Proportion of Students by Group and Total S/U Courses",
    x = "Student Group",
    y = "Proportion",
    color = "Total # of S/U Courses"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5)
  )
total_su_plot
ggsave("figures/total_su_plot.png", plot = total_su_plot, 
       dpi = 300, width = 7, height = 4)
```

```{r}
letter_grades <- c("A+", "A", "A-", 
                   "B+", "B", "B-", 
                   "C+", "C", "C-", 
                   "D+", "D", "D-", 
                   "F")

df_course_SU <- eda_df |>
  group_by(term_enrolled, course_ID, division) |>
  summarise(
    n_total = n(),
    n_letter = sum(final_grade %in% letter_grades, na.rm = TRUE),
    n_SU = sum(final_grade %in% c("S", "U"), na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    prop_letter = n_letter / n_total,
    prop_SU = n_SU / n_total,
    SU_required = prop_letter == 0,
    all_graded = prop_SU == 0
  )

df_term_summary <- df_course_SU |>
  group_by(term_enrolled) |>
  summarise(
    n_courses = n(),
    n_all_graded = sum(all_graded, na.rm = TRUE),
    n_SU_required = sum(SU_required, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    prop_all_graded = n_all_graded / n_courses,
    prop_SU_required = n_SU_required / n_courses,
    prop_partial = 1- prop_all_graded - prop_SU_required
  )

df_term_long <- df_term_summary |>
  dplyr::select(term_enrolled, prop_all_graded, 
                prop_SU_required, prop_partial) |>
  pivot_longer(
    cols = starts_with("prop"),
    names_to = "type",
    values_to = "proportion"
  ) |>
  mutate(
    type = recode(type,
                  prop_all_graded = "All Graded",
                  prop_SU_required = "S/U Required",
                  prop_partial = "At least 1 S/U")
  )

# reduce axis clutter
xvals <- unique(df_term_long$term_enrolled)
xbreaks <- xvals[seq(1, length(xvals), by = 2)]

grade_type_plot <- ggplot(df_term_long, aes(x = term_enrolled, y = proportion, 
                         color = type, group = type)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c(
    "All Graded" = "darkblue",
    "S/U Required" = "green",
    "At least 1 S/U" = "lightgray"
  )) +
  theme_minimal() +
  labs(
    title = "Proportion of Courses by Grading Requirement",
    x = "Term", 
    y = "Proportion of Courses",
    color = "Course Type"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_discrete(breaks = xbreaks)
grade_type_plot
ggsave("figures/grade_type_plot.png", plot = grade_type_plot, dpi = 300)
```
