---
title: "lower lvl classes"
format: pdf
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-libraries
#| message: false
library(lme4)
library(glmnet)
library(pROC)
library(tidymodels)
library(rsample)
library(themis)
library(caret)
library(performance)
library(DHARMa)
library(kableExtra)
library(broom.mixed)
library(tidyverse)
```

```{r}
df <- readRDS("data/model_df.rds")

# Imbalance by student group
df |>
  group_by(catalog_level) |>
  summarise(
    n_total   = n(),
    n_true    = sum(is_SU == "1", na.rm = TRUE),
    n_false   = sum(is_SU == "0", na.rm = TRUE),
    prop_true = mean(is_SU == "1", na.rm = TRUE)
  ) |>
  arrange(desc(prop_true))

df <- df |>
  filter(catalog_level == "100-199" | catalog_level == "200-299") |>
  dplyr::select(-c(term_enrolled, course_ID, estimated, 
                   did_indep_study, student_group, year_enrolled, 
                   max_units, final_grade))

df |>
  count(is_SU) |>
  mutate(prop = n / sum(n))
```

## Train Test Split

```{r}
#| label: train-test-split
set.seed(123)

split <- group_initial_split(df, group = masked_student_ID, prop = 0.8)
train_df <- training(split)
test_df  <- testing(split)

# want to test on students (no data leakage about students)
```

```{r}
best_hyperparam <- readRDS("data/best_hyperparam.rds")
best_thresh <- readRDS("data/best_thresh.rds")
selected_vars <- readRDS("data/selected_vars.rds")

su_recipe_fixed <- recipe(is_SU ~ ., data = train_df) |>
  step_mutate(is_SU = factor(is_SU)) |>
  update_role(masked_student_ID, new_role = "ID") |>  # exclude ID
  step_impute_median(all_numeric_predictors()) |>
  step_impute_mode(all_nominal_predictors()) |>
  step_dummy(all_nominal_predictors(), -has_role("ID"), one_hot = TRUE) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_interact(
    terms = ~ is_natural_sci:starts_with("division_") +
             is_art_humanity:starts_with("division_") +
             is_social_sci:starts_with("division_")
  ) |>
  step_smote(is_SU, over_ratio = best_hyperparam$over_ratio)

baked <- bake(prep(su_recipe_fixed), new_data = NULL)
selected_vars <- intersect(selected_vars, names(baked))

glm_formula <- as.formula(
  paste("is_SU ~", paste(selected_vars, collapse = " + "))
)

glm_fit <- glm(
  glm_formula,
  data = baked,
  family = binomial
)
summary(glm_fit)
```

```{r}
glmer_recipe <- recipe(is_SU ~ ., data = train_df) |>
  update_role(masked_student_ID, new_role = "id") |>
  step_impute_median(all_numeric_predictors()) |>
  step_impute_mode(all_nominal_predictors()) |>
  step_mutate(across(where(is.logical), as.factor)) |>
  step_dummy(all_nominal_predictors(), -all_outcomes(), 
             -masked_student_ID, one_hot = TRUE) |>
  step_interact(
    terms = ~ is_natural_sci:starts_with("division_") +
             is_art_humanity:starts_with("division_") +
             is_social_sci:starts_with("division_")
  ) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_smote(is_SU, over_ratio = best_hyperparam$over_ratio)

trained_recipe <- prep(glmer_recipe, retain = TRUE)
glmer_data <- bake(trained_recipe, new_data = NULL)

selected <- setdiff(selected_vars, c("term_units", "actual_units"))
glm_formula <- as.formula(
  paste0("is_SU ~ ", paste(selected, collapse = " + "), 
         " + (1 | masked_student_ID)")
)

glmer_fit <- glmer(
  glm_formula,
  data = glmer_data,
  family = binomial(link = "logit"),
  control = glmerControl(optimizer = "bobyqa", calc.derivs = FALSE)
)

model_tidy <- tidy(glmer_fit, effects = "fixed", conf.int = TRUE) 
kable(model_tidy, digits = 3, caption = "GLMM Fixed Effects") |>
  kable_styling(full_width = FALSE) |>
  column_spec(1, width = "10em")
```
